--- #YAML:1.0
name:               Image-Nikon-Index
version:            0.01
abstract:           Perl package for indexing Nikon camera image files
author:
    - Snehasis Sinha <snehasis@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Image::ExifTool:  8.60
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
